name: Deploy VitePress site to Pages

on:
  push:
    branches: [master] # 或者 master，取决于你的默认分支名称

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run docs:build # 确保这个命令在你的 package.json 中已定义
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: /.vitepress/dist # 你的构建输出目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2